### PR TITLE
added arg options and QR code generation

### PR DESCRIPTION
**Pull request by sashokbg**
Hello, I am proposing some upgrades to your great tool :)

- Add arguments for
  - hostname
  - presentation dir
  - presentation index file
- More robust injection if client.js
  - Added a wait loop that will wait for the "Reveal" object to be available
  - Waiting for Reval to be initialized before adding hooks
- Transformed to npx executable 
  
- Generation of small QR code that can be scanned to easily open presentation on a mobile

image

Example running with args:
```
npx reveal-notes-server \ 
  --presentationDir=./src \
  --presentationIndex=/presentation.html \
  --hostname=192.168.17.137
```

Please let me know what you think and if things look ok I will add also the README part etc.

Best Regards,
Alex

### CODE REVIEW

**Comment by sashokbg** [comment]
Hello, any update on this PR ?

**Comment by sashokbg** [comment]
Hello @hakimel are you interested in the upgrades I am proposing ? Can you please take a look at the PR ?

**Comment by hakimel** [comment]
The additional options to make this more configurable is great. I don't like the idea of having a QR code overlaid on top of the presentations by default though. Could you change that so it's opt-in? It could either be switched on via config/arg or a keyboard shortcut.

If you want to add keyboard shortcut there's an `Reveal.addKeyBinding` API method that registers the shortcut so that it shows up in the reveal.js help overlay.

```js
Reveal.addKeyBinding( {
    keyCode: 81,
    key: 'Q',
    description: 'Show speaker notes QR code'
}, () => {
    console.log('show qr code')
} )
```

Sorry for taking forever to get back on this, @sashokbg.

**Comment by hakimel** [comment]
I didn't realize the code hides automatically when the notes window connects. With that in mind I'm fine with leaving this on by default, as long as there's a way to disable it :)

**Comment by sashokbg** [comment]
Hello @hakimel I have added a client option that can disable the QR code.
I also updated the Readme md

Let me know what you think.
Have a nice weekend

**Comment by sashokbg** [comment]
Hello @hakimel a small reminder about this feature :)
Does it look good to you ?

**Comment by hakimel** [comment]
Thanks for adding the config option! This has been merged but I'm going to make a minor tweak. Will update here shortly.

**Comment by sashokbg** [comment]
Thank you for your help @hakimel. Could you increment and publish the new version to npm please ?

**Pull request merged**
